@host = http://localhost:3000/api/comments
@token = Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..5Tt9rccOaD2jMjQL.Ge3p8q9u-wvUCZ2H_79Ow28bKuyUsfrL-GmV_YBCnQ4TIGpwQiXnN_zJZddEUXTFMwRslGw6tOUUTu9vBPyMwaUKgWDhvtYoPJx7E3TeF6vM_MbFTUyFM36LYES7rNelpeO5LRjrs3K27obJwyDCDEN_k1O2NkIXa4A8qZHrTo23Ai-_dc80e_ydhhx-pV0cralJONeqDEJ9DMll-r_M5hBtXm3iNPlu4bBlNGM8vqIVb0Y6ULaPy2nCULEE2WBWnTkvBviQdNES86Ux5K3d.XRR5soT7O8eLLL-xYRH4vQ


### Get all comments of particular post
GET {{host}}/post/clh6ck5hm000v90dkywz4lu1k?skip=0
Authorization: {{token}}


### create comment
POST {{host}}
Authorization: {{token}}
Content-Type: application/json

{
  "message": "comment 23",
  "postId": "clh6ck5hm000v90dkywz4lu1k"
}


### update comment
PUT {{host}}/clhbst6gl000190z8r1ojvq0p
Authorization: {{token}}
Content-Type: application/json

{
  "message": "comment 1 edited"
}


### Delete comment
DELETE {{host}}/clhbst6gl000190z8r1ojvq0p
Authorization: {{token}}
