@host = http://localhost:3000/api/posts
@token = Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..0XrleZMiZzTZ0Jy8.GzZo5SxtlEux2K3xF1eCn45K3tsDyfbadwe3yTu20N9ToNyE0lIJ7zW60VQncZVPVoiGUUL3UhUDvEnW7jBHaRUZc4yMxGG_gaSb96H0Hsl8aqx4YHo0j8alrzdugjzhXX7NevHSKzV73eB-n3NR_jRCKht0Jx9IRHtV407cN9X5J5jVaY-yRFTrynCZKHKbEekH4XXUs10WCuws6LIu2qasGTHX_B7UQ4quGqip5NpQ9H7CLF6Wws6B2LSqaP9IAsySS3MSk4iLJuG2_tSYbw.VZB0aMx34U-cGBPH5xIX8Q


### Get all posts
GET {{host}}
Authorization: {{token}}


### Get post by id
GET {{host}}/clfgd9udj000890uk0g04llly
Authorization: {{token}}


### Create 
POST {{host}}
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Title 2",
  "description": "description description description description"
}


### Update
PUT {{host}}
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Title 4 edited",
  "id": "clfgd9udj000890uk0g04llly"
}


### Delete
DELETE {{host}}/clfgd9udj000890uk0g04llly
Authorization: {{token}}
