@host = http://localhost:3000/api/posts
@token = Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..5Tt9rccOaD2jMjQL.Ge3p8q9u-wvUCZ2H_79Ow28bKuyUsfrL-GmV_YBCnQ4TIGpwQiXnN_zJZddEUXTFMwRslGw6tOUUTu9vBPyMwaUKgWDhvtYoPJx7E3TeF6vM_MbFTUyFM36LYES7rNelpeO5LRjrs3K27obJwyDCDEN_k1O2NkIXa4A8qZHrTo23Ai-_dc80e_ydhhx-pV0cralJONeqDEJ9DMll-r_M5hBtXm3iNPlu4bBlNGM8vqIVb0Y6ULaPy2nCULEE2WBWnTkvBviQdNES86Ux5K3d.XRR5soT7O8eLLL-xYRH4vQ


### Get all posts
GET {{host}}?skip=0
Authorization: {{token}}


### Get all posts of particular user
GET {{host}}/user?skip=0
Authorization: {{token}}


### Get post by id
GET {{host}}/clh6cjin1000l90dkh2r0m561
Authorization: {{token}}


### Create 
POST {{host}}
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Title 15",
  "description": "description description description description"
}


### Update
PUT {{host}}
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Title 10 edited",
  "id": "clh6cjin1000l90dkh2r0m561"
}


### Delete
DELETE {{host}}/clh6cjin1000l90dkh2r0m561
Authorization: {{token}}
